# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy
    - make clean

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

release:
  name_template: "Bitcart CLI v{{.Version}}"

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true
  name_template: "{{ .ProjectName }}.src"

archives:
  - formats: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i686
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

dockers_v2:
  - images:
      - "ghcr.io/bitcart/bitcart-cli"
    tags:
      - latest
      - "{{ .Tag }}"
    dockerfile: Dockerfile
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.description: "Bitcart CLI is a command-line interface for interacting with Bitcart daemons and developing plugins"
    annotations:
      "index:org.opencontainers.image.description": "Bitcart CLI is a command-line interface for interacting with Bitcart daemons and developing plugins"

docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
